# Generated by Django 5.2.6 on 2025-12-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_visibility',
            field=models.CharField(choices=[('Public', 'Can be seen by anyone'), ('Private', 'I can only see it')], default='Public', max_length=10),
        ),
    ]
