# Generated by Django 5.2.6 on 2025-12-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_photo_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='incentive',
            field=models.TextField(blank=True),
        ),
    ]
