# Generated by Django 5.2.7 on 2025-12-09 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_incentive'),
        ('rideshareapp', '0006_reportedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='rideshareapp.cio'),
        ),
    ]
