# Generated by Django 5.2.6 on 2025-12-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_driverreview'),
        ('posts', '0005_post_cio'),
    ]

    operations = [
    ]
