# Generated by Django 4.2.27 on 2025-12-10 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0005_post_cio"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="passengers",
            field=models.ManyToManyField(
                blank=True, related_name="joined_rides", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
