# Generated by Django 4.2.27 on 2025-12-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_merge_0005_driverreview_0005_post_cio"),
        ("posts", "0006_post_passengers"),
    ]

    operations = []
