# Generated by Django 5.2.7 on 2025-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='dm',
            field=models.BooleanField(default=False),
        ),
    ]
