# Generated by Django 5.2.7 on 2025-11-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='computing_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
