# Generated by Django 5.2.7 on 2025-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_nickname_profile_sustainability_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="sustainability_interests",
            field=models.TextField(),
        ),
    ]
