# Generated by Django 5.2.7 on 2025-12-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_sustainability_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
