# Generated by Django 5.2.7 on 2025-11-22 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideshareapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cio",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="cio",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="cios", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="cio",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="CIOPlaceholderMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholder_members",
                        to="rideshareapp.cio",
                    ),
                ),
            ],
        ),
    ]
