# Generated by Django 5.2.7 on 2025-12-09 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_sustainability_interests'),
        ('rideshareapp', '0002_remove_cio_created_at_alter_cio_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('room', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('message_author_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
