# Generated by Django 5.2.7 on 2025-12-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshareapp', '0004_remove_reportedmessage_message_author_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedmessage',
            name='room',
            field=models.TextField(),
        ),
    ]
